include $(GOROOT)/src/Make.inc

TARG = ircd-novo
GOFILES = \
	client.go \
	client_registry.go \
	config.go \
	dns.go \
	hash.go \
	ircd.go \
	ircd_novo.go \
	listeners.go \
	match.go \
	message_handler.go \
	misc.go \
	numerics.go \
	parser.go \
	version.go \

include $(GOROOT)/src/Make.cmd
