include $(GOROOT)/src/Make.inc

TARG = ircd-novo
GOFILES = \
	client_connection_handler.go \
	ircd.go \
	ircd_novo.go \
	listeners.go \
	misc.go \
	numerics.go \
	raw_message.go \
	version.go \

include $(GOROOT)/src/Make.cmd
